-- List all the tables in the schema
SELECT table_name FROM information_schema.tables


--select * from INFORMATION_SCHEMA.TABLES
--alter table dbo.COM_Address with check check constraint all

SELECT 'alter table dbo.' + table_name + ' with check check constraint all' FROM information_schema.tables where table_type='BASE TABLE' order by table_name


alter table dbo._importOrdersToUAT with check check constraint all
alter table dbo._tmp_CurrentUsersInDev with check check constraint all
alter table dbo.Analytics_Campaign with check check constraint all
alter table dbo.Analytics_Conversion with check check constraint all
alter table dbo.Analytics_ConversionCampaign with check check constraint all
alter table dbo.Analytics_DayHits with check check constraint all
alter table dbo.Analytics_ExitPages with check check constraint all
alter table dbo.Analytics_HourHits with check check constraint all
alter table dbo.Analytics_Index with check check constraint all
alter table dbo.Analytics_MonthHits with check check constraint all
alter table dbo.Analytics_Statistics with check check constraint all
alter table dbo.Analytics_WeekHits with check check constraint all
alter table dbo.Analytics_YearHits with check check constraint all
alter table dbo.BadWords_Word with check check constraint all
alter table dbo.BadWords_WordCulture with check check constraint all
alter table dbo.Blog_Comment with check check constraint all
alter table dbo.Blog_PostSubscription with check check constraint all
alter table dbo.Board_Board with check check constraint all
alter table dbo.Board_Message with check check constraint all
alter table dbo.Board_Moderator with check check constraint all
alter table dbo.Board_Role with check check constraint all
alter table dbo.Board_Subscription with check check constraint all
alter table dbo.cashbacktemp with check check constraint all
alter table dbo.Chat_InitiatedChatRequest with check check constraint all
alter table dbo.Chat_Message with check check constraint all
alter table dbo.Chat_Notification with check check constraint all
alter table dbo.Chat_OnlineSupport with check check constraint all
alter table dbo.Chat_OnlineUser with check check constraint all
alter table dbo.Chat_PopupWindowSettings with check check constraint all
alter table dbo.Chat_Room with check check constraint all
alter table dbo.Chat_RoomUser with check check constraint all
alter table dbo.Chat_SupportCannedResponse with check check constraint all
alter table dbo.Chat_SupportTakenRoom with check check constraint all
alter table dbo.Chat_User with check check constraint all
alter table dbo.CMS_AbuseReport with check check constraint all
alter table dbo.CMS_ACL with check check constraint all
alter table dbo.CMS_ACLItem with check check constraint all
alter table dbo.CMS_AllowedChildClasses with check check constraint all
alter table dbo.CMS_AlternativeForm with check check constraint all
alter table dbo.CMS_Attachment with check check constraint all
alter table dbo.CMS_AttachmentForEmail with check check constraint all
alter table dbo.CMS_AttachmentHistory with check check constraint all
alter table dbo.CMS_AutomationHistory with check check constraint all
alter table dbo.CMS_AutomationState with check check constraint all
alter table dbo.CMS_Avatar with check check constraint all
alter table dbo.CMS_Badge with check check constraint all
alter table dbo.CMS_BannedIP with check check constraint all
alter table dbo.CMS_Banner with check check constraint all
alter table dbo.CMS_BannerCategory with check check constraint all
alter table dbo.CMS_Category with check check constraint all
alter table dbo.CMS_Class with check check constraint all
alter table dbo.CMS_ClassMapping with check check constraint all
alter table dbo.CMS_ClassSite with check check constraint all
alter table dbo.CMS_Country with check check constraint all
alter table dbo.CMS_CssStylesheet with check check constraint all
alter table dbo.CMS_CssStylesheetSite with check check constraint all
alter table dbo.CMS_Culture with check check constraint all
alter table dbo.CMS_DeviceProfile with check check constraint all
alter table dbo.CMS_DeviceProfileLayout with check check constraint all
alter table dbo.CMS_Document with check check constraint all
alter table dbo.CMS_DocumentAlias with check check constraint all
alter table dbo.CMS_DocumentCategory with check check constraint all
alter table dbo.CMS_DocumentTag with check check constraint all
alter table dbo.CMS_Email with check check constraint all
alter table dbo.CMS_EmailAttachment with check check constraint all
alter table dbo.CMS_EmailTemplate with check check constraint all
alter table dbo.CMS_EmailUser with check check constraint all
alter table dbo.CMS_EventLog with check check constraint all
alter table dbo.CMS_Form with check check constraint all
alter table dbo.CMS_FormRole with check check constraint all
alter table dbo.CMS_FormUserControl with check check constraint all
alter table dbo.CMS_InlineControl with check check constraint all
alter table dbo.CMS_InlineControlSite with check check constraint all
alter table dbo.CMS_Layout with check check constraint all
alter table dbo.CMS_LicenseKey with check check constraint all
alter table dbo.CMS_MacroRule with check check constraint all
alter table dbo.CMS_Membership with check check constraint all
alter table dbo.CMS_MembershipRole with check check constraint all
alter table dbo.CMS_MembershipUser with check check constraint all
alter table dbo.CMS_MetaFile with check check constraint all
alter table dbo.CMS_ObjectRelationship with check check constraint all
alter table dbo.CMS_ObjectSettings with check check constraint all
alter table dbo.CMS_ObjectVersionHistory with check check constraint all
alter table dbo.CMS_ObjectWorkflowTrigger with check check constraint all
alter table dbo.CMS_OpenIDUser with check check constraint all
alter table dbo.CMS_PageTemplate with check check constraint all
alter table dbo.CMS_PageTemplateCategory with check check constraint all
alter table dbo.CMS_PageTemplateScope with check check constraint all
alter table dbo.CMS_PageTemplateSite with check check constraint all
alter table dbo.CMS_Permission with check check constraint all
alter table dbo.CMS_Personalization with check check constraint all
alter table dbo.CMS_Query with check check constraint all
alter table dbo.CMS_Relationship with check check constraint all
alter table dbo.CMS_RelationshipName with check check constraint all
alter table dbo.CMS_RelationshipNameSite with check check constraint all
alter table dbo.CMS_Resource with check check constraint all
alter table dbo.CMS_ResourceSite with check check constraint all
alter table dbo.CMS_ResourceString with check check constraint all
alter table dbo.CMS_ResourceTranslation with check check constraint all
alter table dbo.CMS_Role with check check constraint all
alter table dbo.CMS_RolePermission with check check constraint all
alter table dbo.CMS_RoleUIElement with check check constraint all
alter table dbo.CMS_ScheduledTask with check check constraint all
alter table dbo.CMS_SearchEngine with check check constraint all
alter table dbo.CMS_SearchIndex with check check constraint all
alter table dbo.CMS_SearchIndexCulture with check check constraint all
alter table dbo.CMS_SearchIndexSite with check check constraint all
alter table dbo.CMS_SearchTask with check check constraint all
alter table dbo.CMS_Session with check check constraint all
alter table dbo.CMS_SettingsCategory with check check constraint all
alter table dbo.CMS_SettingsKey with check check constraint all
alter table dbo.CMS_Site with check check constraint all
alter table dbo.CMS_SiteCulture with check check constraint all
alter table dbo.CMS_SiteDomainAlias with check check constraint all
alter table dbo.CMS_SMTPServer with check check constraint all
alter table dbo.CMS_SMTPServerSite with check check constraint all
alter table dbo.CMS_State with check check constraint all
alter table dbo.CMS_Tag with check check constraint all
alter table dbo.CMS_TagGroup with check check constraint all
alter table dbo.CMS_TemplateDeviceLayout with check check constraint all
alter table dbo.CMS_TimeZone with check check constraint all
alter table dbo.CMS_Transformation with check check constraint all
alter table dbo.CMS_TranslationService with check check constraint all
alter table dbo.CMS_TranslationSubmission with check check constraint all
alter table dbo.CMS_TranslationSubmissionItem with check check constraint all
alter table dbo.CMS_Tree with check check constraint all
alter table dbo.CMS_UICulture with check check constraint all
alter table dbo.CMS_UIElement with check check constraint all
alter table dbo.CMS_User with check check constraint all
alter table dbo.CMS_UserCulture with check check constraint all
alter table dbo.CMS_UserRole with check check constraint all
alter table dbo.CMS_UserSettings with check check constraint all
alter table dbo.CMS_UserSite with check check constraint all
alter table dbo.CMS_VersionAttachment with check check constraint all
alter table dbo.CMS_VersionHistory with check check constraint all
alter table dbo.CMS_WebFarmServer with check check constraint all
alter table dbo.CMS_WebFarmServerTask with check check constraint all
alter table dbo.CMS_WebFarmTask with check check constraint all
alter table dbo.CMS_WebPart with check check constraint all
alter table dbo.CMS_WebPartCategory with check check constraint all
alter table dbo.CMS_WebPartContainer with check check constraint all
alter table dbo.CMS_WebPartContainerSite with check check constraint all
alter table dbo.CMS_WebPartLayout with check check constraint all
alter table dbo.CMS_WebTemplate with check check constraint all
alter table dbo.CMS_Widget with check check constraint all
alter table dbo.CMS_WidgetCategory with check check constraint all
alter table dbo.CMS_WidgetRole with check check constraint all
alter table dbo.CMS_Workflow with check check constraint all
alter table dbo.CMS_WorkflowAction with check check constraint all
alter table dbo.CMS_WorkflowHistory with check check constraint all
alter table dbo.CMS_WorkflowScope with check check constraint all
alter table dbo.CMS_WorkflowStep with check check constraint all
alter table dbo.CMS_WorkflowStepRoles with check check constraint all
alter table dbo.CMS_WorkflowStepUser with check check constraint all
alter table dbo.CMS_WorkflowTransition with check check constraint all
alter table dbo.CMS_WorkflowUser with check check constraint all
alter table dbo.COM_Address with check check constraint all
alter table dbo.COM_Bundle with check check constraint all
alter table dbo.COM_Currency with check check constraint all
alter table dbo.COM_CurrencyExchangeRate with check check constraint all
alter table dbo.COM_Customer with check check constraint all
alter table dbo.COM_CustomerCreditHistory with check check constraint all
alter table dbo.COM_Department with check check constraint all
alter table dbo.COM_DepartmentTaxClass with check check constraint all
alter table dbo.COM_DiscountCoupon with check check constraint all
alter table dbo.COM_DiscountLevel with check check constraint all
alter table dbo.COM_DiscountLevelDepartment with check check constraint all
alter table dbo.COM_ExchangeTable with check check constraint all
alter table dbo.COM_InternalStatus with check check constraint all
alter table dbo.COM_Manufacturer with check check constraint all
alter table dbo.COM_OptionCategory with check check constraint all
alter table dbo.COM_Order with check check constraint all
alter table dbo.COM_OrderItem with check check constraint all
alter table dbo.COM_OrderItemSKUFile with check check constraint all
alter table dbo.COM_OrderStatus with check check constraint all
alter table dbo.COM_OrderStatusUser with check check constraint all
alter table dbo.COM_PaymentOption with check check constraint all
alter table dbo.COM_PaymentShipping with check check constraint all
alter table dbo.COM_PublicStatus with check check constraint all
alter table dbo.COM_ShippingCost with check check constraint all
alter table dbo.COM_ShippingOption with check check constraint all
alter table dbo.COM_ShippingOptionTaxClass with check check constraint all
alter table dbo.COM_ShoppingCart with check check constraint all
alter table dbo.COM_ShoppingCartSKU with check check constraint all
alter table dbo.COM_SKU with check check constraint all
alter table dbo.COM_SKUDiscountCoupon with check check constraint all
alter table dbo.COM_SKUFile with check check constraint all
alter table dbo.COM_SKUOptionCategory with check check constraint all
alter table dbo.COM_SKUTaxClasses with check check constraint all
alter table dbo.COM_Supplier with check check constraint all
alter table dbo.COM_TaxClass with check check constraint all
alter table dbo.COM_TaxClassCountry with check check constraint all
alter table dbo.COM_TaxClassState with check check constraint all
alter table dbo.COM_UserDepartment with check check constraint all
alter table dbo.COM_VolumeDiscount with check check constraint all
alter table dbo.COM_Wishlist with check check constraint all
alter table dbo.Community_Friend with check check constraint all
alter table dbo.Community_Group with check check constraint all
alter table dbo.Community_GroupMember with check check constraint all
alter table dbo.Community_GroupRolePermission with check check constraint all
alter table dbo.Community_Invitation with check check constraint all
alter table dbo.CONTENT_Blog with check check constraint all
alter table dbo.CONTENT_BlogMonth with check check constraint all
alter table dbo.CONTENT_BlogPost with check check constraint all
alter table dbo.CONTENT_FAQ with check check constraint all
alter table dbo.CONTENT_File with check check constraint all
alter table dbo.CONTENT_MenuItem with check check constraint all
alter table dbo.CONTENT_News with check check constraint all
alter table dbo.CONTENT_PressRelease with check check constraint all
alter table dbo.CONTENT_Product with check check constraint all
alter table dbo.custom_wdm_accessory_module_gallery with check check constraint all
alter table dbo.custom_wdm_accessory_module_headline with check check constraint all
alter table dbo.custom_wdm_accessory_module_specs with check check constraint all
alter table dbo.custom_wdm_product_module_2_col_comp with check check constraint all
alter table dbo.custom_wdm_product_module_3_col_comp with check check constraint all
alter table dbo.custom_wdm_product_module_3_col_comp_2 with check check constraint all
alter table dbo.custom_wdm_product_module_360 with check check constraint all
alter table dbo.custom_wdm_product_module_4_col_comp with check check constraint all
alter table dbo.custom_wdm_product_module_accessory with check check constraint all
alter table dbo.custom_wdm_product_module_article_6_img with check check constraint all
alter table dbo.custom_wdm_product_module_article_lg_img with check check constraint all
alter table dbo.custom_wdm_product_module_feature_basic_information with check check constraint all
alter table dbo.custom_wdm_product_module_feature_fw_bottom with check check constraint all
alter table dbo.custom_wdm_product_module_feature_fw_left with check check constraint all
alter table dbo.custom_wdm_product_module_feature_fw_right with check check constraint all
alter table dbo.custom_wdm_product_module_feature_fw_top with check check constraint all
alter table dbo.custom_wdm_product_module_feature_sm_left with check check constraint all
alter table dbo.custom_wdm_product_module_feature_sm_right with check check constraint all
alter table dbo.custom_wdm_product_module_front_back with check check constraint all
alter table dbo.custom_wdm_product_module_fw_slider with check check constraint all
alter table dbo.custom_wdm_product_module_fw_slider_slide with check check constraint all
alter table dbo.custom_wdm_product_module_headline with check check constraint all
alter table dbo.custom_wdm_product_module_related_links with check check constraint all
alter table dbo.custom_wdm_product_module_related_links_default with check check constraint all
alter table dbo.custom_wdm_product_module_sample_image with check check constraint all
alter table dbo.custom_wdm_product_module_specs with check check constraint all
alter table dbo.custom_wdm_product_module_video with check check constraint all
alter table dbo.custom_wdm_products_category with check check constraint all
alter table dbo.custom_wdm_products_product with check check constraint all
alter table dbo.custom_wdm_products_range with check check constraint all
alter table dbo.custom_wdm_single_product_tab with check check constraint all
alter table dbo.customtable_blog_categories with check check constraint all
alter table dbo.customtable_wdm_related_links_default with check check constraint all
alter table dbo.Events_Attendee with check check constraint all
alter table dbo.Export_History with check check constraint all
alter table dbo.Export_Task with check check constraint all
alter table dbo.Form_Olympus_CleaningSurvey_1 with check check constraint all
alter table dbo.Form_Olympus_Contactus with check check constraint all
alter table dbo.Form_Olympus_Promotion_CashBackSummer with check check constraint all
alter table dbo.Form_Olympus_Promotion_OlympusMegaCashBack with check check constraint all
alter table dbo.Form_Olympus_Promotion_OlympusOMDBonusSamsoniteLuggagePromotion with check check constraint all
alter table dbo.Form_Olympus_Promotion_OlympusOMDEM5BonusSamsoniteBackpack with check check constraint all
alter table dbo.Form_Olympus_Promotion_OMDEM1BonusAccessoriesPromotion with check check constraint all
alter table dbo.Form_Olympus_Promotion_ProfessionalDictationTradein with check check constraint all
alter table dbo.Form_Olympus_PromotionThePerfectPairOMD with check check constraint all
alter table dbo.Form_Olympus_PromotionThePerfectPairPENBonus with check check constraint all
alter table dbo.Form_Olympus_ServiceRepairForm with check check constraint all
alter table dbo.Form_Olympus_TEST with check check constraint all
alter table dbo.Form_Olympus_TestForm with check check constraint all
alter table dbo.Form_Olympus_TestSurvey with check check constraint all
alter table dbo.Forums_Attachment with check check constraint all
alter table dbo.Forums_Forum with check check constraint all
alter table dbo.Forums_ForumGroup with check check constraint all
alter table dbo.Forums_ForumModerators with check check constraint all
alter table dbo.Forums_ForumPost with check check constraint all
alter table dbo.Forums_ForumRoles with check check constraint all
alter table dbo.Forums_ForumSubscription with check check constraint all
alter table dbo.Forums_UserFavorites with check check constraint all
alter table dbo.Integration_Connector with check check constraint all
alter table dbo.Integration_Synchronization with check check constraint all
alter table dbo.Integration_SyncLog with check check constraint all
alter table dbo.Integration_Task with check check constraint all
alter table dbo.Media_File with check check constraint all
alter table dbo.Media_Library with check check constraint all
alter table dbo.Media_LibraryRolePermission with check check constraint all
alter table dbo.Messaging_ContactList with check check constraint all
alter table dbo.Messaging_IgnoreList with check check constraint all
alter table dbo.Messaging_Message with check check constraint all
alter table dbo.Newsletter_ABTest with check check constraint all
alter table dbo.Newsletter_Emails with check check constraint all
alter table dbo.Newsletter_EmailTemplate with check check constraint all
alter table dbo.Newsletter_EmailTemplateNewsletter with check check constraint all
alter table dbo.Newsletter_Link with check check constraint all
alter table dbo.Newsletter_Newsletter with check check constraint all
alter table dbo.Newsletter_NewsletterIssue with check check constraint all
alter table dbo.Newsletter_OpenedEmail with check check constraint all
alter table dbo.Newsletter_Subscriber with check check constraint all
alter table dbo.Newsletter_SubscriberLink with check check constraint all
alter table dbo.Newsletter_SubscriberNewsletter with check check constraint all
alter table dbo.Notification_Gateway with check check constraint all
alter table dbo.Notification_Subscription with check check constraint all
alter table dbo.Notification_Template with check check constraint all
alter table dbo.Notification_TemplateText with check check constraint all
alter table dbo.Olympus_ConsumerElecStores with check check constraint all
alter table dbo.Olympus_Countries with check check constraint all
alter table dbo.Olympus_FAQ with check check constraint all
alter table dbo.Olympus_FeaturedProduct with check check constraint all
alter table dbo.Olympus_GalleryAlbum with check check constraint all
alter table dbo.Olympus_HomepageFeature with check check constraint all
alter table dbo.Olympus_HomepagePromotionalBanner with check check constraint all
alter table dbo.Olympus_HouseholdIncome with check check constraint all
alter table dbo.Olympus_ImportantFeatures with check check constraint all
alter table dbo.Olympus_InformationSources with check check constraint all
alter table dbo.Olympus_Occupations with check check constraint all
alter table dbo.Olympus_OtherCameraBrands with check check constraint all
alter table dbo.Olympus_Product_Accessories1 with check check constraint all
alter table dbo.Olympus_Product_Accessories2 with check check constraint all
alter table dbo.Olympus_Product_Accessories3 with check check constraint all
alter table dbo.Olympus_Product_Accessories4 with check check constraint all
alter table dbo.Olympus_Product_Audio with check check constraint all
alter table dbo.Olympus_Product_Binoculars with check check constraint all
alter table dbo.Olympus_Product_Bodies1 with check check constraint all
alter table dbo.Olympus_Product_Bodies2 with check check constraint all
alter table dbo.Olympus_Product_CablesandRemotes with check check constraint all
alter table dbo.Olympus_Product_CasesandStraps with check check constraint all
alter table dbo.Olympus_Product_ConversionLenses with check check constraint all
alter table dbo.Olympus_Product_DigitalCameras with check check constraint all
alter table dbo.Olympus_Product_DigitalCompact with check check constraint all
alter table dbo.Olympus_Product_DirectRecording with check check constraint all
alter table dbo.Olympus_Product_DSLR_Lenses with check check constraint all
alter table dbo.Olympus_Product_EasyFun with check check constraint all
alter table dbo.Olympus_Product_FilmCameras with check check constraint all
alter table dbo.Olympus_Product_FlashSystem1 with check check constraint all
alter table dbo.Olympus_Product_FlashSystem2 with check check constraint all
alter table dbo.Olympus_Product_Image with check check constraint all
alter table dbo.Olympus_Product_Lenses2 with check check constraint all
alter table dbo.Olympus_Product_Microcassette with check check constraint all
alter table dbo.Olympus_Product_MusicPlayers with check check constraint all
alter table dbo.Olympus_Product_Notetakers with check check constraint all
alter table dbo.Olympus_Product_PEN with check check constraint all
alter table dbo.Olympus_Product_PEN_Lens with check check constraint all
alter table dbo.Olympus_Product_PowerandBatteries with check check constraint all
alter table dbo.Olympus_Product_Software with check check constraint all
alter table dbo.Olympus_Product_SportsOutdoors with check check constraint all
alter table dbo.Olympus_Product_StylePrecision with check check constraint all
alter table dbo.Olympus_Product_ToughEveryday with check check constraint all
alter table dbo.Olympus_Product_Transcription with check check constraint all
alter table dbo.Olympus_Product_UnderwaterHousings with check check constraint all
alter table dbo.Olympus_Product_VoiceMusic with check check constraint all
alter table dbo.Olympus_Product_xDMedia with check check constraint all
alter table dbo.Olympus_ProductFeature with check check constraint all
alter table dbo.Olympus_ProductInterests with check check constraint all
alter table dbo.Olympus_ProductInterestsFuture with check check constraint all
alter table dbo.Olympus_ProductInterestsFutureEmails with check check constraint all
alter table dbo.Olympus_ProductModel with check check constraint all
alter table dbo.Olympus_ProductRegistrationLastPurchase with check check constraint all
alter table dbo.Olympus_ProductRegistrationOverseasPurchase with check check constraint all
alter table dbo.Olympus_ProductSpecCategoryHeading with check check constraint all
alter table dbo.Olympus_ProductSpecDefinition with check check constraint all
alter table dbo.Olympus_ProductSpecification with check check constraint all
alter table dbo.Olympus_ProductSpecLabel with check check constraint all
alter table dbo.Olympus_ProductTab360 with check check constraint all
alter table dbo.Olympus_ProductTabAccessories with check check constraint all
alter table dbo.Olympus_ProductTabAwards with check check constraint all
alter table dbo.Olympus_ProductTabFeaturesCloseUp with check check constraint all
alter table dbo.Olympus_ProductTabGallery with check check constraint all
alter table dbo.Olympus_ProductTabSampleShot with check check constraint all
alter table dbo.Olympus_ProductUpdates with check check constraint all
alter table dbo.Olympus_PromoForm with check check constraint all
alter table dbo.Olympus_PromoLog with check check constraint all
alter table dbo.Olympus_Promotion with check check constraint all
alter table dbo.Olympus_PromotionCashback with check check constraint all
alter table dbo.Olympus_PromotionLog with check check constraint all
alter table dbo.Olympus_PromotionRetailer with check check constraint all
alter table dbo.Olympus_PromotionStrip with check check constraint all
alter table dbo.Olympus_PromotionTile with check check constraint all
alter table dbo.Olympus_PurchaseInfluences with check check constraint all
alter table dbo.Olympus_PurchaseLocations with check check constraint all
alter table dbo.Olympus_RegisteredProducts with check check constraint all
alter table dbo.Olympus_Repairs with check check constraint all
alter table dbo.Olympus_SocialLink with check check constraint all
alter table dbo.Olympus_SpareParts with check check constraint all
alter table dbo.Olympus_Specification with check check constraint all
alter table dbo.Olympus_Support with check check constraint all
alter table dbo.OM_ABTest with check check constraint all
alter table dbo.OM_ABVariant with check check constraint all
alter table dbo.OM_Account with check check constraint all
alter table dbo.OM_AccountContact with check check constraint all
alter table dbo.OM_AccountStatus with check check constraint all
alter table dbo.OM_Activity with check check constraint all
alter table dbo.OM_ActivityType with check check constraint all
alter table dbo.OM_Contact with check check constraint all
alter table dbo.OM_ContactGroup with check check constraint all
alter table dbo.OM_ContactGroupMember with check check constraint all
alter table dbo.OM_ContactRole with check check constraint all
alter table dbo.OM_ContactStatus with check check constraint all
alter table dbo.OM_IP with check check constraint all
alter table dbo.OM_Membership with check check constraint all
alter table dbo.OM_MVTCombination with check check constraint all
alter table dbo.OM_MVTCombinationVariation with check check constraint all
alter table dbo.OM_MVTest with check check constraint all
alter table dbo.OM_MVTVariant with check check constraint all
alter table dbo.OM_PageVisit with check check constraint all
alter table dbo.OM_PersonalizationVariant with check check constraint all
alter table dbo.OM_Rule with check check constraint all
alter table dbo.OM_Score with check check constraint all
alter table dbo.OM_ScoreContactRule with check check constraint all
alter table dbo.OM_Search with check check constraint all
alter table dbo.OM_UserAgent with check check constraint all
alter table dbo.PM_Project with check check constraint all
alter table dbo.PM_ProjectRolePermission with check check constraint all
alter table dbo.PM_ProjectStatus with check check constraint all
alter table dbo.PM_ProjectTask with check check constraint all
alter table dbo.PM_ProjectTaskPriority with check check constraint all
alter table dbo.PM_ProjectTaskStatus with check check constraint all
alter table dbo.Polls_Poll with check check constraint all
alter table dbo.Polls_PollAnswer with check check constraint all
alter table dbo.Polls_PollRoles with check check constraint all
alter table dbo.Polls_PollSite with check check constraint all
alter table dbo.Reporting_Report with check check constraint all
alter table dbo.Reporting_ReportCategory with check check constraint all
alter table dbo.Reporting_ReportGraph with check check constraint all
alter table dbo.Reporting_ReportSubscription with check check constraint all
alter table dbo.Reporting_ReportTable with check check constraint all
alter table dbo.Reporting_ReportValue with check check constraint all
alter table dbo.Reporting_SavedGraph with check check constraint all
alter table dbo.Reporting_SavedReport with check check constraint all
alter table dbo.Staging_Server with check check constraint all
alter table dbo.Staging_Synchronization with check check constraint all
alter table dbo.Staging_SyncLog with check check constraint all
alter table dbo.Staging_Task with check check constraint all
alter table dbo.Temp_File with check check constraint all
